name: Check pull request

on:
    pull_request:
        branches:
            - main
            - "patch/**"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Lorg13/project1
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --group lint

      - name: Ruff check
        run: uv run ruff check src --output-format=github

      - name: MyPy
        run: |
            uv run mypy src \
              --config-file pyproject.toml \
              --output=json \
              | jq -r '"::error title=Mypy issue,file=\(.file),line=\(.line),col=\(.column)::\(.message)"'

      - name: Bandit
        run: uv run bandit src -r -n 3 -lll
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Lorg13/project1
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --group test

      - name: Run pytest
        run: |
          uv run pytest tests \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            -v -s

      - name: Upload test results
        if:  ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
